### ISSUE TITLE
obasic.com hangs when saving with a lowercase filename 

### ISSUE THREAD

**Issue by dddfffggg777** [ivanizag/iz-cpm#7]
obasic.com
"save" command gives error
![image](https://user-images.githubusercontent.com/114140927/208281171-d83e90cb-6907-4d33-a106-9db356e855ed.png)

**Comment by ivanizag** [comment]
I managed to reproduce it when saving with a file name with lowercase letters:
```
44531 Bytes free
BASIC Rev. 4.51
[CP/M Version]
Copyright 1977 (C) by Microsoft
Ok
10 print 1
save "UPPER"
[[BDOS command 26: F_DMAOFF(4725)]][[BDOS command 19: F_DELETE(4700)]][[Delete file UPPER.BAS]][[=>00]]
[[BDOS command 22: F_MAKE(4700)]][[Create file UPPER.BAS]][[=>00]]
[[BDOS command 26: F_DMAOFF(4725)]][[BDOS command 21: F_WRITE(4700)]][Write record 0 from 4725][[=>00]]
[[BDOS command 26: F_DMAOFF(4725)]][[BDOS command 16: F_CLOSE(4700)]][[=>00]]
Ok

save "lower"
[[BDOS command 26: F_DMAOFF(4725)]][[BDOS command 19: F_DELETE(4700)]][[Delete file lower.BAS]][[=>ff]]
[[BDOS command 22: F_MAKE(4700)]][[Create file lower.BAS]][[=>00]]
[[BDOS command 26: F_DMAOFF(4725)]][[BDOS command 21: F_WRITE(4700)]][Write record 0 from 4725][[=>01]]
Disk I/O error[[BDOS command 26: F_DMAOFF(4725)]][[BDOS command 21: F_WRITE(4700)]][Write record 1 from 4725][[=>01]]
Disk I/O error[[BDOS command 26: F_DMAOFF(4725)]][[BDOS command 21: F_WRITE(4700)]][Write record 2 from 4725][[=>01]]
Disk I/O error[[BDOS command 26: F_DMAOFF(4725)]][[BDOS command 21: F_WRITE(4700)]][Write record 3 from 4725][[=>01]]
Disk I/O error[[BDOS command 26: F_DMAOFF(4725)]][[BDOS command 21: F_WRITE(4700)]][Write record 4 from 4725][[=>01]]

```

**Comment by ivanizag** [comment]
OBASIC does not convert to uppercase (as CCP and most programs do) and can generate files that are hard to delete. See https://groups.google.com/g/comp.os.cpm/c/BZGKhIFNWjo

CP/M file directories can be upper and lower case, but for iz-cpm to be convenient to deal with host files that are usually in lowercase, i internally transform to uppercase. See https://github.com/ivanizag/iz-cpm/blob/master/src/fcb.rs#L213

Removing that line, the problem is solved for OBASIC.COM. But it turns less convenient with most other programs.
I'll have to think what is the best solution. Meanwhile, saving works when using all uppercase file names.

**Comment by dddfffggg777** [comment]
the error kills source code of basic program!
